set:
  features: false
  train: false
  eval: false
  test: false

path:
  work_path: /home/ydc/DACSE2021/sed-tim-base/workplace
  root_dir:  /home/ydc/DACSE2021/task5/data/Development_Set
  train_dir: ${path.root_dir}/Training_Set
  eval_dir:  ${path.root_dir}/Validation_Set
  test_dir:  /home/ydc/DACSE2021/task5/data/Evaluation_Set
  feat_path: /home/ydc/code/dcase-few-shot-bioacoustic-main/workplace/Features
  feat_train: ${path.feat_path}/feat_train
  feat_eval:  ${path.feat_path}/feat_eval
  feat_test:  ${path.feat_path}/feat_test
features:
  seg_len: 0.200
  hop_seg: 0.050
  eps: 2.220446049250313e-16
  fmax: 11025
  fmin: 50
  sr: 22050
  n_fft: 1024
  n_mels: 128
  hop_mel: 256
train:
  num_classes: 15
  num_query: 10
  n_shot: 5
  k_way : 10
  device: cuda
  lr_rate: 0.0001
  scheduler_gamma: 0.5
  scheduler_step_size: 10
  epochs: 14

eval:
  samples_neg: 650
  iterations: 3
  query_batch_size: 50
  negative_set_batch_size : 50



